name: workflow_practice
on: push

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
      - uses: actions/checkout@v4
      - name: run command
      - run: echo "hello noor"
      
