name: basic linux
on: workflow_dispatch

jobs :
  build :
  runs-on:
    ubuntu-latest
    
    steps: 
      - name : show dir
        run : pwd
      - name : show hidden
        run : ls -a
    

  


